In [1]:
import pandas as pd

dataset = pd.read_csv("50_Startups.csv")
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [2]:
dataset = pd.get_dummies(dataset).astype(int)
dataset = dataset.drop(columns=['State_California'])
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349,136897,471784,192261,0,1
1,162597,151377,443898,191792,0,0
2,153441,101145,407934,191050,1,0
3,144372,118671,383199,182901,0,1
4,142107,91391,366168,166187,1,0
5,131876,99814,362861,156991,0,1
6,134615,147198,127716,156122,0,0
7,130298,145530,323876,155752,1,0
8,120542,148718,311613,152211,0,1
9,123334,108679,304981,149759,0,0
10,101913,110594,229160,146121,1,0
11,100671,91790,249744,144259,0,0
12,93863,127320,249839,141585,1,0
13,91992,135495,252664,134307,0,0
14,119943,156547,256512,132602,1,0
15,114523,122616,261776,129917,0,1
16,78013,121597,264346,126992,0,0
17,94657,145077,282574,125370,0,1
18,91749,114175,294919,124266,1,0
19,86419,153514,0,122776,0,1
20,76253,113867,298664,118474,0,0
21,78389,153773,299737,111313,0,1
22,73994,122782,303319,110352,1,0
23,67532,105751,304768,108733,1,0
24,77044,99281,140574,108552,0,1
25,64664,139553,137962,107404,0,0
26,75328,144135,134050,105733,1,0
27,72107,127864,353183,105008,0,1
28,66051,182645,118148,103282,1,0
29,65605,153032,107138,101004,0,1
30,61994,115641,91131,99937,1,0
31,61136,152701,88218,97483,0,1
32,63408,129219,46085,97427,0,0
33,55493,103057,214634,96778,1,0
34,46426,157693,210797,96712,0,0
35,46014,85047,205517,96479,0,1
36,28663,127056,201126,90708,1,0
37,44069,51283,197029,89949,0,0
38,20229,65947,185265,81229,0,1
39,38558,82982,174999,81005,0,0
40,28754,118546,172795,78239,0,0
41,27892,84710,164470,77798,1,0
42,23640,96189,148001,71498,0,0
43,15505,127382,35534,69758,0,1
44,22177,154806,28334,65200,0,0
45,1000,124153,1903,64926,0,1
46,1315,115816,297114,49490,1,0
47,0,135426,0,42559,0,0
48,542,51743,0,35673,0,1
49,0,116983,45173,14681,0,0

In [3]:
independent = dataset[['R&D Spend','Administration','Marketing Spend','State_Florida','State_New York']]
dependent = dataset[['Profit']]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size=0.3, random_state=0)

In [85]:
from sklearn.svm import SVR #importing the Linear regression library from sklearn
# regressor = SVR(kernel='linear', C=0.1)
# regressor = SVR(kernel='linear', C=1)
# regressor = SVR(kernel='linear', C=10)

# regressor = SVR(kernel='rbf', C=0.1)
# regressor = SVR(kernel='rbf', C=1)
# regressor = SVR(kernel='rbf', C=10)

# regressor = SVR(kernel='poly', C=0.1)
# regressor = SVR(kernel='poly', C=1)
# regressor = SVR(kernel='poly', C=10)

# regressor = SVR(kernel='sigmoid', C=0.1)
# regressor = SVR(kernel='sigmoid', C=1)
# regressor = SVR(kernel='sigmoid', C=10)

regressor = SVR(kernel='linear', C=0.1)
regressor.fit(X_train, Y_train)

C:\Users\z030703\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=0.1, kernel='linear')

In [76]:
coefficients = regressor.coef_
coefficients

AttributeError: coef_ is only available when using a linear kernel

In [86]:
Y_pred = regressor.predict(X_test)
Y_pred

array([102017.94872363, 133149.23709614, 133526.0591348 ,  73291.53468044,
       179391.8080147 , 113702.6230057 ,  67861.66795202,  97254.91464861,
       113718.242853  , 169228.02087982,  96521.85856397,  88779.65306969,
       109785.47972233,  89279.92668827, 127457.31157549])

In [87]:
from sklearn.metrics import r2_score # for r2 score evaluvation importing the function from metrics library

r_score= r2_score(Y_test,Y_pred) # comparing the predicted values and test(Actual) values to calculate R2Score 
r_score

0.9408798822563795

In [47]:
Y_train_pred = regressor.predict(X_train)
Y_train_pred

array([108857.07676754, 111805.25694333,  28694.47306881,  26982.30265866,
        81320.22245846, 103630.31248532,  79787.92729245,  91545.32389889,
        60620.51866208,  22377.00059567,  50905.47813473,  38251.39750729,
       100298.63060055,  79707.14323483,  73147.57722531, 101174.33940182,
        76519.11814938,  23386.42631588,  17871.85234127, 120212.38176022,
        82346.24827633,  34383.46962033,  86104.49931393, 156753.8855444 ,
        39299.04765377,  17305.50822506,  54075.51432858, 128910.89018307,
       104061.16062985,  33500.8631445 , -35669.62721195, 111649.55381833,
       117037.25181637,  28152.92503415,  48129.37104855])

In [48]:
r_score_train= r2_score(Y_train,Y_train_pred) # comparing the predicted values and test(Actual) values to calculate R2Score 
r_score_train

-0.2642496787164357